/** Generated from the authoritative Access form: frmEmployeeSearch3Holding. */
export const EMPLOYEE_SEARCH_ACCESS_COLUMNS = [
  {"key":"ActionSelect","label":"Select","order":0,"width":24,"accessHidden":false},
  {"key":"EmEntryUserName","label":"Entry User","order":1,"width":37,"accessHidden":false},
  {"key":"EmEntryDate","label":"Entry Date","order":2,"width":79,"accessHidden":false},
  {"key":"WhereEmployeeFound","label":"Where Found","order":3,"width":79,"accessHidden":false},
  {"key":"EmHowReferred","label":"How Ref","order":4,"width":58,"accessHidden":false},
  {"key":"PayrollCoOnSiteInitials_IPG","label":"IPG","order":5,"width":30,"accessHidden":false},
  {"key":"JobApplicationStatus_IPG","label":"IPG Job App Status","order":6,"width":37,"accessHidden":false},
  {"key":"PostEmployeeAsAvailableDate","label":"Post Employee as Available Date","order":7,"width":79,"accessHidden":true},
  {"key":"PayrollCoOnSiteID","label":"PayrollCoOnSiteID","order":8,"width":142,"accessHidden":true},
  {"key":"PayrollCoOnSiteColorID","label":"PayrollCoOnSiteColorID","order":9,"width":175,"accessHidden":true},
  {"key":"JobApplicationStatusIDUserName_IPG","label":"IPG Job App Status User","order":10,"width":173,"accessHidden":true},
  {"key":"JobApplicationStatusIDDate_IPG","label":"IPG Job App Status Date","order":11,"width":79,"accessHidden":false},
  {"key":"EmEmployeeStatus","label":"Employee Status","order":12,"width":130,"accessHidden":true},
  {"key":"Spare1","label":" ","order":13,"width":67,"accessHidden":true},
  {"key":"EmFirstName","label":"First Name","order":14,"width":86,"accessHidden":false},
  {"key":"EmMiddle","label":"MI","order":15,"width":24,"accessHidden":false},
  {"key":"EmLastName","label":"Last Name","order":16,"width":86,"accessHidden":false},
  {"key":"EmHomePhone","label":"Home Phone","order":17,"width":58,"accessHidden":false},
  {"key":"EmStreet","label":"Street","order":18,"width":65,"accessHidden":true},
  {"key":"EmployeeNoCommunicationText","label":"No Communication","order":19,"width":24,"accessHidden":false},
  {"key":"WeekEndingDate","label":"Week Ending","order":20,"width":79,"accessHidden":false},
  {"key":"EmCity","label":"City","order":21,"width":100,"accessHidden":false},
  {"key":"EmState","label":"State","order":22,"width":60,"accessHidden":false},
  {"key":"EmMobilePhone","label":"Cell # 1","order":23,"width":96,"accessHidden":false},
  {"key":"EmMobilePhoneVerifyText","label":"Cell # 1 Verify","order":24,"width":113,"accessHidden":true},
  {"key":"EmGrade","label":"Grade","order":25,"width":51,"accessHidden":true},
  {"key":"TextMsgAddress","label":"Text Msg Add 1","order":26,"width":198,"accessHidden":true},
  {"key":"EmReferredBy","label":"Ref By","order":27,"width":67,"accessHidden":true},
  {"key":"AvgHrsWorked","label":"Average Hrs Worked per Week","order":28,"width":51,"accessHidden":false},
  {"key":"FirstDateOnJob","label":"FDA              First Date Assigned","order":29,"width":79,"accessHidden":false},
  {"key":"TotalHoursWorked","label":"THW             Total Hours Worked","order":30,"width":65,"accessHidden":false},
  {"key":"LicenseExpDateFlag","label":"License Exp Date Flag","order":31,"width":75,"accessHidden":true},
  {"key":"Spare4","label":" ","order":32,"width":24,"accessHidden":true},
  {"key":"Spare6","label":" ","order":33,"width":24,"accessHidden":true},
  {"key":"EmNote2","label":"Note 2","order":34,"width":254,"accessHidden":true},
  {"key":"EmNote1","label":"Note 1","order":35,"width":266,"accessHidden":true},
  {"key":"EmNote3","label":"Note 3","order":36,"width":37,"accessHidden":true},
  {"key":"EmEmail","label":"Email","order":37,"width":198,"accessHidden":true},
  {"key":"SubTrade1ID","label":"SubTrade1ID","order":38,"width":96,"accessHidden":true},
  {"key":"EmployeeID","label":"EmployeeID","order":39,"width":103,"accessHidden":true},
  {"key":"SubTrade2ID","label":"SubTrade2ID","order":40,"width":96,"accessHidden":true},
  {"key":"ClusterID","label":"ClusterID","order":41,"width":79,"accessHidden":true},
  {"key":"WhereEmployeeFoundIDUserName","label":"Where Found User","order":42,"width":79,"accessHidden":true},
  {"key":"SubTrade3ID","label":"SubTrade3ID","order":43,"width":96,"accessHidden":true},
  {"key":"Cluster","label":"Cluster","order":44,"width":79,"accessHidden":true},
  {"key":"SubTrade4ID","label":"SubTrade4ID","order":45,"width":96,"accessHidden":true},
  {"key":"EmployeeNotesHistory","label":"Emp Notes","order":46,"width":95,"accessHidden":true},
  {"key":"SubTrade1","label":"Sub Trade 1","order":47,"width":114,"accessHidden":true},
  {"key":"WhereEmployeeFoundIDDate","label":"Where Found Date","order":48,"width":83,"accessHidden":true},
  {"key":"SubTrade2","label":"Sub Trade 2","order":49,"width":114,"accessHidden":true},
  {"key":"PayRate","label":"Pay Rate","order":50,"width":81,"accessHidden":true},
  {"key":"SubTrade3","label":"Sub Trade 3","order":51,"width":114,"accessHidden":true},
  {"key":"SubTrade4","label":"Sub Trade 4","order":52,"width":114,"accessHidden":true},
  {"key":"WhereEmployeeFoundIDTime","label":"Where Found Time","order":53,"width":82,"accessHidden":true},
  {"key":"PayrollCoOnSiteID_IPG","label":"PayrollCoOnSiteID_IPG","order":54,"width":170,"accessHidden":true},
  {"key":"JobAppAuditNotes","label":"Job App Audit Notes","order":55,"width":345,"accessHidden":true},
  {"key":"EmployeeNoCommUserName","label":"No Comm 1 User","order":56,"width":130,"accessHidden":true},
  {"key":"HealthInsurance_IPG","label":"IPG Health Ins","order":57,"width":37,"accessHidden":true},
  {"key":"EmployeeFutureCall","label":"Future Call","order":58,"width":79,"accessHidden":true},
  {"key":"EmployeeDuplicate","label":"Em Duplicate","order":59,"width":81,"accessHidden":true},
  {"key":"EmployeeNoCommunicationUserName","label":"No Communication User","order":60,"width":37,"accessHidden":true},
  {"key":"EmployeeNoCommDate","label":"No Comm 1 Date","order":61,"width":131,"accessHidden":true},
  {"key":"EmployeeNoCommunicationTimestamp","label":"No Communication Date","order":62,"width":79,"accessHidden":true},
  {"key":"CallNumberID","label":"CallNumberID","order":63,"width":96,"accessHidden":true},
  {"key":"PayrollCoOnSiteInitials","label":"Payroll Co On Site This Week","order":64,"width":34,"accessHidden":true},
  {"key":"EmployeeNoCommUserName2","label":"No Comm 2 User","order":65,"width":130,"accessHidden":true},
  {"key":"Spare2","label":" ","order":66,"width":24,"accessHidden":true},
  {"key":"Car","label":"Car","order":67,"width":86,"accessHidden":true},
  {"key":"Spare3","label":" ","order":68,"width":45,"accessHidden":true},
  {"key":"Spare8","label":" ","order":69,"width":30,"accessHidden":true},
  {"key":"Spare7","label":" ","order":70,"width":30,"accessHidden":true},
  {"key":"EmployeeNoCommUserName3","label":"No Comm 3 User","order":71,"width":130,"accessHidden":true},
  {"key":"EmCellCarrier","label":"Cell Carrier 1","order":72,"width":96,"accessHidden":true},
  {"key":"PostEmployeeAsAvailableText","label":"Post Employee as Available","order":73,"width":85,"accessHidden":true},
  {"key":"CallNumberIDTime","label":"Call # Time","order":74,"width":65,"accessHidden":true},
  {"key":"TruePeopleMatch","label":"True People Match","order":75,"width":96,"accessHidden":true},
  {"key":"PostEmployeeAsAvailableUserName","label":"Post Employee as Available User","order":76,"width":52,"accessHidden":true},
  {"key":"EmployeeNoComm2Text","label":"No Comm 2","order":77,"width":30,"accessHidden":true},
  {"key":"EmployeeReturnToSender","label":"RTS (Return to Sender)","order":78,"width":86,"accessHidden":true},
  {"key":"LicenseStatus","label":"License Status","order":79,"width":83,"accessHidden":true},
  {"key":"CTLevel","label":"Level (for CT)","order":80,"width":339,"accessHidden":true},
  {"key":"EmployeeNoCommDate3","label":"No Comm 3 Date","order":81,"width":131,"accessHidden":true},
  {"key":"Salesman","label":"Salesman","order":82,"width":96,"accessHidden":true},
  {"key":"EmployeeNotesCount","label":"EmployeeNotesCount","order":83,"width":96,"accessHidden":true},
  {"key":"EmMobilePhone2","label":"Cell # 2","order":84,"width":96,"accessHidden":true},
  {"key":"Placeholder","label":"Placeholder","order":85,"width":96,"accessHidden":true},
  {"key":"LicenseAge","label":"License Age","order":86,"width":71,"accessHidden":true},
  {"key":"LicenseIssueDate","label":"License Issue Date","order":87,"width":111,"accessHidden":true},
  {"key":"EmployeeOnUnemploymentText","label":"Employee on Unemployment (UI)","order":88,"width":50,"accessHidden":true},
  {"key":"EmployeeOnUnemploymentUserName","label":"Employee on Unemployment (UI) User","order":89,"width":72,"accessHidden":true},
  {"key":"EmployeeRIP","label":"RIP","order":90,"width":86,"accessHidden":true},
  {"key":"EmTrade","label":"Trade","order":91,"width":110,"accessHidden":false},
  {"key":"EmQualification","label":"Qualification","order":92,"width":94,"accessHidden":false},
  {"key":"Spare10","label":" ","order":93,"width":37,"accessHidden":false},
  {"key":"EmployeeContactHistoryUserName","label":"Last Action User","order":94,"width":162,"accessHidden":true},
  {"key":"PayrollCoOnSiteColorID_IPG","label":"PayrollCoOnSiteColorID_IPG","order":95,"width":79,"accessHidden":true},
  {"key":"BusinessName","label":"Business Name","order":96,"width":179,"accessHidden":true},
  {"key":"LicenseObtainedByMethod","label":"License Obtained By Method","order":97,"width":100,"accessHidden":true},
  {"key":"EmployeeOnUnemploymentDate","label":"Employee on Unemployment (UI) Date","order":98,"width":100,"accessHidden":true},
  {"key":"CountOfCellNumbers","label":"# of Cell Numbers","order":99,"width":65,"accessHidden":true},
  {"key":"EmployeeNoCommUserName4","label":"No Comm 4 User","order":100,"width":100,"accessHidden":true},
  {"key":"EmployeeFutureCallUserName","label":"Future Call User","order":101,"width":58,"accessHidden":true},
  {"key":"EmZip","label":"Zip","order":102,"width":55,"accessHidden":true},
  {"key":"EmMobilePhone3","label":"Cell # 3","order":103,"width":96,"accessHidden":true},
  {"key":"EmployeeProfileType","label":"Profile Type","order":104,"width":96,"accessHidden":true},
  {"key":"EmployeeFutureCallUserDate","label":"Future Call User Date","order":105,"width":79,"accessHidden":true},
  {"key":"EmployeeUserFlag1","label":"User Flag 1","order":106,"width":94,"accessHidden":true},
  {"key":"EmployeeOnUnemploymentNotesHistory","label":"Employee on Unemployment (UI) History","order":107,"width":84,"accessHidden":true},
  {"key":"LicenseNumber","label":"License Number","order":108,"width":75,"accessHidden":true},
  {"key":"PostEmployeeAsAvailableNotesHistory","label":"Post Employee as Available History","order":109,"width":64,"accessHidden":true},
  {"key":"EmployeeUserFlag2","label":"User Flag 2","order":110,"width":94,"accessHidden":true},
  {"key":"EmployeeNoCommDate4","label":"No Comm 4 Date","order":111,"width":131,"accessHidden":true},
  {"key":"TextMsgAddress2","label":"Text Msg Add 2","order":112,"width":79,"accessHidden":true},
  {"key":"TextMsgAddress3","label":"Text Msg Add 3","order":113,"width":79,"accessHidden":true},
  {"key":"EmployeeUserFlag3","label":"User Flag 3","order":114,"width":94,"accessHidden":true},
  {"key":"TextMsgAddress4","label":"Text Msg Add 4","order":115,"width":79,"accessHidden":true},
  {"key":"EmployeeUserFlag4","label":"User Flag 4","order":116,"width":94,"accessHidden":true},
  {"key":"LicenseIssueDateYear","label":"License Issue Year","order":117,"width":109,"accessHidden":true},
  {"key":"EmMobilePhone4","label":"Cell # 4","order":118,"width":96,"accessHidden":true},
  {"key":"LicenseIssueDateUserName","label":"License Issue Date User","order":119,"width":142,"accessHidden":true},
  {"key":"Spare5","label":" ","order":120,"width":24,"accessHidden":true},
  {"key":"EmployeeSales","label":"11 Sales","order":121,"width":72,"accessHidden":true},
  {"key":"Spare9","label":" ","order":122,"width":24,"accessHidden":true},
  {"key":"Covid19VaccinationStatus","label":"Vax","order":123,"width":25,"accessHidden":true},
  {"key":"EmployeeNoComm3Text","label":"No Comm 3","order":124,"width":30,"accessHidden":true},
  {"key":"NumActionsCustomLetter","label":"Letter (# of Custom Letter actions)","order":125,"width":58,"accessHidden":true},
  {"key":"Covid19VaccinationStatusIDUserName","label":"Vax User","order":126,"width":82,"accessHidden":true},
  {"key":"Snapshot","label":"Work History Snapshot","order":127,"width":85,"accessHidden":true},
  {"key":"SiteName","label":"Job Name","order":128,"width":80,"accessHidden":true},
  {"key":"EmployeeNoComm4Text","label":"No Comm 4","order":129,"width":30,"accessHidden":true},
  {"key":"Covid19VaccinationStatusIDDate","label":"Vax Date","order":130,"width":96,"accessHidden":true},
  {"key":"EmStateCityID","label":"State","order":131,"width":96,"accessHidden":true},
  {"key":"Covid19VaccinationStatusHistory","label":"Vax History","order":132,"width":98,"accessHidden":true},
  {"key":"TruePeopleMatchIDUserName","label":"True People Match User","order":133,"width":115,"accessHidden":true},
  {"key":"TruePeopleMatchIDDate","label":"True People Match Date","order":134,"width":116,"accessHidden":true},
  {"key":"WeeksAway","label":"Weeks Away","order":135,"width":97,"accessHidden":true},
  {"key":"CustomerBusName","label":"Customer Assignment","order":136,"width":265,"accessHidden":true},
  {"key":"EmExperience","label":"Experience","order":137,"width":97,"accessHidden":true},
  {"key":"YearsInTrade","label":"Years in Trade","order":138,"width":114,"accessHidden":true},
  {"key":"EmLicensedIn","label":"Lic-State","order":139,"width":74,"accessHidden":true},
  {"key":"OSHA10Status","label":"OSHA 10 Status","order":140,"width":57,"accessHidden":true},
  {"key":"EmployeeContactHistoryDate","label":"Last Action Date","order":141,"width":79,"accessHidden":true},
  {"key":"EmployeeContactHistoryActionType","label":"Last Action","order":142,"width":79,"accessHidden":true},
  {"key":"EmployeeContactHistoryNote","label":"Last Action Note","order":143,"width":114,"accessHidden":true},
  {"key":"NumActionsCustomText","label":"Text (# of Custom Text actions)","order":144,"width":55,"accessHidden":true},
  {"key":"NumActionsCustomPostcard","label":"P Cards (# of Custom Postcard actions)","order":145,"width":73,"accessHidden":true},
  {"key":"SiteState","label":"Job State","order":146,"width":76,"accessHidden":true},
  {"key":"PhoneNeedsValidation","label":"Phone Needs Validation","order":147,"width":178,"accessHidden":true},
  {"key":"EmployeeOnUnemploymentTimestamp","label":"Employee on Unemployment (UI) Timestamp","order":148,"width":80,"accessHidden":true},
  {"key":"EmployeeTimesheetRequestText","label":"Timesheet Request","order":149,"width":63,"accessHidden":true},
  {"key":"EmployeeTimesheetRequestUserName","label":"Timesheet Request User","order":150,"width":87,"accessHidden":true},
  {"key":"EmployeeTimesheetRequestDate","label":"Timesheet Request Date","order":151,"width":92,"accessHidden":true},
  {"key":"EmployeeTimesheetRequestCount","label":"EmployeeTimesheetRequestCount","order":152,"width":244,"accessHidden":true},
  {"key":"EmployeeTimesheetRequestHistory","label":"Timesheet Request History","order":153,"width":116,"accessHidden":true},
  {"key":"S1","label":"S1","order":154,"width":96,"accessHidden":true},
  {"key":"S1IDUserName","label":"S1 User","order":155,"width":73,"accessHidden":true},
  {"key":"S1IDDate","label":"S1 Date","order":156,"width":96,"accessHidden":true},
  {"key":"S1History","label":"S1 History","order":157,"width":89,"accessHidden":true},
  {"key":"S2","label":"S2","order":158,"width":96,"accessHidden":true},
  {"key":"S2IDUserName","label":"S2 User","order":159,"width":73,"accessHidden":true},
  {"key":"S2IDDate","label":"S2 Date","order":160,"width":96,"accessHidden":true},
  {"key":"S2History","label":"S2 History","order":161,"width":89,"accessHidden":true},
  {"key":"EmployeeUserFlag5","label":"User Flag 5","order":162,"width":80,"accessHidden":true},
  {"key":"EmployeeUserFlag6","label":"User Flag 6","order":163,"width":94,"accessHidden":true},
  {"key":"EmployeeUserFlag7","label":"User Flag 7","order":164,"width":96,"accessHidden":true},
  {"key":"EmployeeUserFlag8","label":"User Flag 8","order":165,"width":94,"accessHidden":true},
  {"key":"OnlineJobAppFolder","label":"Online Job App Folder","order":166,"width":165,"accessHidden":true},
  {"key":"HLinkResume","label":"Resume Link","order":167,"width":105,"accessHidden":true},
  {"key":"Resume","label":"Resume","order":168,"width":80,"accessHidden":true},
  {"key":"InterviewedByDate","label":"Interview Date","order":169,"width":120,"accessHidden":true},
  {"key":"WorkNumber","label":"Work #","order":170,"width":96,"accessHidden":true},
  {"key":"InterviewNumber","label":"Interview #","order":171,"width":96,"accessHidden":true},
  {"key":"InterviewedBy","label":"Interviewed By","order":172,"width":50,"accessHidden":true},
  {"key":"InterviewedByIDUserName","label":"Interviewed By User","order":173,"width":114,"accessHidden":true},
  {"key":"InterviewedByIDDate","label":"Interviewed By Date","order":174,"width":79,"accessHidden":true},
  {"key":"InterviewedByLocation","label":"Interview Location","order":175,"width":120,"accessHidden":true},
  {"key":"WillTravel","label":"Will Travel","order":176,"width":80,"accessHidden":true},
  {"key":"ResumeNumber","label":"Resume #","order":177,"width":80,"accessHidden":true},
  {"key":"PPE","label":"PPE","order":178,"width":80,"accessHidden":true},
  {"key":"ResumeNumberIDUserName","label":"Resume # User","order":179,"width":119,"accessHidden":true},
  {"key":"ResumeNumberIDDate","label":"Resume # Date","order":180,"width":120,"accessHidden":true},
  {"key":"ReasonForLeavingNumber","label":"Leaving #","order":181,"width":96,"accessHidden":true},
  {"key":"EmployeeFirstCallNumber","label":"1st Call #","order":182,"width":101,"accessHidden":true},
  {"key":"EmployeeFirstCallNumberIDUserName","label":"1st Call # User","order":183,"width":113,"accessHidden":true},
  {"key":"EmployeeFirstCallNumberIDDate","label":"1st Call # Date","order":184,"width":114,"accessHidden":true},
  {"key":"CallNumberHistory","label":"Call # History","order":185,"width":37,"accessHidden":false},
  {"key":"CallNumberNoteCount","label":"CallNumberNoteCount","order":186,"width":30,"accessHidden":false},
  {"key":"CallNumberIDUserName","label":"Call # User","order":187,"width":37,"accessHidden":false},
  {"key":"CallNumberIDDate","label":"Call # Date","order":188,"width":79,"accessHidden":false},
  {"key":"CallNumber","label":"[Feature 813] Call #","order":189,"width":44,"accessHidden":false},
  {"key":"EmployeeNoCommDate2","label":"No Comm 2 Date","order":190,"width":131,"accessHidden":true},
  {"key":"LastCallUserName","label":"Call User","order":191,"width":96,"accessHidden":true},
  {"key":"EmQualificationID","label":"EmQualificationID","order":192,"width":40,"accessHidden":true},
  {"key":"LastCallDate","label":"Call Date","order":193,"width":96,"accessHidden":true},
  {"key":"EmTradeID","label":"EmTradeID","order":194,"width":40,"accessHidden":true},
  {"key":"EmployeeNoCommText","label":"No Comm 1","order":195,"width":30,"accessHidden":true},
  {"key":"EmHowReferredID","label":"EmHowReferredID","order":196,"width":40,"accessHidden":true},
  {"key":"LastCallNote","label":"Call Note","order":197,"width":190,"accessHidden":false},
  {"key":"CountyFilter","label":"County Filter","order":198,"width":108,"accessHidden":true},
  {"key":"IDTitleDriversLicense","label":"ID Drivers License","order":199,"width":137,"accessHidden":true},
  {"key":"ResumeNumberID","label":"ResumeNumberID","order":200,"width":80,"accessHidden":true},
  {"key":"EmEmail2","label":"Email 2","order":201,"width":155,"accessHidden":true},
  {"key":"EmEmail3","label":"Email 3","order":202,"width":155,"accessHidden":true},
  {"key":"IDTitleDriversLicenseOnFile","label":"ID Drivers License on File","order":203,"width":182,"accessHidden":true},
  {"key":"HasEmergencyContact","label":"Has Emergency Contact","order":204,"width":171,"accessHidden":true},
  {"key":"EmEmail4","label":"Email 4","order":205,"width":155,"accessHidden":true},
  {"key":"InterviewNumberID","label":"InterviewNumberID","order":206,"width":80,"accessHidden":true},
  {"key":"EmEmail5","label":"Email 5","order":207,"width":155,"accessHidden":true},
  {"key":"Vonage","label":"Vonage","order":208,"width":227,"accessHidden":true},
  {"key":"EmEmail6","label":"Email 6","order":209,"width":155,"accessHidden":true},
  {"key":"SchoolCompleted","label":"School Completed","order":210,"width":141,"accessHidden":true},
] as const;
