"use client";

import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { AccessButton } from "@/components/access/AccessButton";

type VacationRow={first:string;last:string;mi:string;payroll:string;year:string;perHr:string;start:string;vac:string;work:string;firstJob:string;firstWE:string;firstPayroll:string;lastPayroll:string;total:string;regular:string;ot:string};
const ROWS:VacationRow[]=[
 ["Jack","Ven","S","IPG","2026","$0.93","10/11/2024","40","50","10/5/2024","11/17/2023","11/17/2023","7/24/2026","1060","1038","22"],
 ["Jeff","Paquiot","S","IPG","2026","$0.66","9/3/2021","40","50","8/30/2021","7/19/2019","7/19/2019","7/24/2026","748.5","725","23.5"],
 ["John","Yanovitch Jr","P","IPG","2026","$1.49","5/27/2022","80","25","5/23/2022","1/13/2017","1/13/2017","7/24/2026","296","287.5","8.5"],
 ["Joseph","Palma","J","IPG","2026","$0.00","8/31/2018","","25","8/27/2018","7/19/2013","7/19/2013","5/15/2026","646.5","624.5","22"],
 ["Nicholas","Fogarty","J","IPG","2026","$1.20","10/18/2024","40","50","10/14/2024","2/14/2020","2/14/2020","7/24/2026","1053","1053","0"],
 ["Paul","Forde","C","IPG","2026","$1.22","6/21/2019","","25","6/17/2019","12/11/2015","12/11/2015","7/24/2026","526.5","525.5","1"],
].map(([first,last,mi,payroll,year,perHr,start,vac,work,firstJob,firstWE,firstPayroll,lastPayroll,total,regular,ot])=>({first,last,mi,payroll,year,perHr,start,vac,work,firstJob,firstWE,firstPayroll,lastPayroll,total,regular,ot}));

export function VacationHoursReportScreen(){
 const router=useRouter();const [name,setName]=useState("");const [payroll,setPayroll]=useState("IPG");const [year,setYear]=useState("2026");const [view,setView]=useState("View 01");
 const rows=useMemo(()=>ROWS.filter(r=>(!name||`${r.first} ${r.last}`.toLowerCase().includes(name.toLowerCase()))&&(!payroll||r.payroll===payroll)&&(!year||r.year===year)),[name,payroll,year]);
 const clear=()=>{setName("");setPayroll("")};
 return <section className="ac-vacation"><header className="ac-vacation-header"><h1>Vacation Hours Report - All</h1><div className="ac-vacation-view"><label>View:</label><select value={view} onChange={e=>setView(e.target.value)}>{["View 01","View 02","View 03","View 04","View 05","View 06","View 07","View 08","View 09","View 10","View 17"].map(v=><option key={v}>{v}</option>)}</select><AccessButton>Save View</AccessButton><AccessButton>Delete View</AccessButton><AccessButton>Refresh</AccessButton><AccessButton onClick={()=>window.print()}>Export View</AccessButton><label className="assign">Assign Year<select value={year} onChange={e=>setYear(e.target.value)}><option>2026</option><option>2025</option><option>2024</option></select></label><AccessButton className="find">⌕</AccessButton></div><select className="ac-vacation-company" value={payroll} onChange={e=>setPayroll(e.target.value)}><option value="IPG">IPG</option><option value="">All</option></select><div className="ac-vacation-close"><AccessButton onClick={()=>router.push("/tracking")}>Cancel</AccessButton><button aria-label="Help">?</button></div></header>
 <div className="ac-vacation-tools"><div className="ac-vacation-filters"><label>Search in Name:<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Payroll Company<select value={payroll} onChange={e=>setPayroll(e.target.value)}><option value=""/><option>IPG</option></select><em>(for title on Export View)</em></label></div><div className="ac-vacation-presets">{["Default","View 02","View 03","View 04","View 05","View 06","View 07","View 08","View 09","View 10","","","","","","","View 17"].map((v,i)=><AccessButton key={i} onClick={()=>v&&setView(v==="Default"?"View 01":v)}>{v}</AccessButton>)}</div><AccessButton className="ac-vacation-clear" onClick={clear}>Clear Filters</AccessButton></div>
 <div className="ac-vacation-grid-wrap"><table className="ac-vacation-grid"><thead><tr>{["","First Name","Last Name","MI","Payroll Co","Assign Year","Vac Per Hr","Vac Start Date","Hrs Vac","Work Hrs = 1 Hr Vac","First Date on Job","First WE","First WE in Payroll Co","Last WE in Payroll Co","Total Hours To Date","Total Reg Hours To Date","Total OT Hours To Date","Total"].map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.first}-${r.last}`} className={i===0?"is-current":undefined}><td/><td>{r.first}</td><td>{r.last}</td><td>{r.mi}</td><td className="payroll">{r.payroll}</td><td>{r.year}</td><td><b>{r.perHr}</b></td><td className="date">{r.start}</td><td><b>{r.vac}</b></td><td><b>{r.work}</b></td><td>{r.firstJob}</td><td><b>{r.firstWE}</b></td><td><b>{r.firstPayroll}</b></td><td className="date">{r.lastPayroll}</td><td><b>{r.total}</b></td><td><b>{r.regular}</b></td><td><b>{r.ot}</b></td><td/></tr>)}</tbody></table></div><footer className="ac-vacation-record">Record:　|◀　◀　 <input value={rows.length?1:0} readOnly aria-label="Record number"/> of {rows.length}　▶　▶|　　<span>▽ Filtered</span>　 <b>Search</b></footer></section>;
}
