"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { initialReportDate, ReportWeekControls } from "./ReportWeekControls";
const payroll=["Regular Payroll Report","Detailed Payroll Report","Payroll Check Notes Report","Payroll Check Notes","Copy Forward","Payroll Adjustments","Payroll Report - XcelHR","Payroll Report Search","Payroll Export Report","Rates and Invoice Total","Payroll Crosschecks","Payroll State Crosscheck"];
const sales=["Sales Report","Sales Report Breakdown","20% Rule Report","20% Rule Report for Salesman","Commissions Report","Commissions Main View","Commissions for Salesman","Cluster Comm. Main View","Cluster Comm. for Salesman"];
const jobs=["All Jobs","Current Jobs","Job Employees","T Sheets HL","OCIP Jobs","Rate Jobs","Shift Differential Jobs","WCC Rates Report","Compare Company Tracking Weeks","Check Weekly Rates","Deleted Employees","Weekly Certified Payroll","New Report Search","Seamus Open Invoices","AR Report","All Employees on a Job","Edit List of Cities","Edit List of Clusters","Mileage Log","Company Contacts"];
const links:Record<string,string>={"AR Report":"/accounts-receivable","All Jobs":"/jobs","Current Jobs":"/current-jobs","Job Employees":"/employees-in-tracking","All Employees on a Job":"/employees-in-tracking","Company Contacts":"/customers","Seamus Open Invoices":"/open-invoices","Website Access":"/website-application"};
export function AccessReportsScreen(){const router=useRouter();const [date,setDate]=useState(initialReportDate);const [message,setMessage]=useState("");function button(label:string){return <button key={label} className={label==="Payroll Report Search"?"report-cyan":label==="Payroll Export Report"?"report-red":label.startsWith("Cluster")?"report-alert":""} onClick={()=>links[label]?router.push(links[label]):setMessage(`${label} has not been connected to its Access report query yet.`)}>{label}</button>;}function group(title:string,items:string[]){return <fieldset className={`report-group report-${title.toLowerCase().replaceAll(" ","-")}`}><h2>========={title}=========</h2>{items.map(button)}</fieldset>;}return <section className="access-report-screen"><header><h1>Reports</h1><button onClick={()=>router.push("/tracking")}>Close</button></header><ReportWeekControls date={date} onChange={setDate}/><div className="report-launchers">{jobs.map(button)}</div><div className="report-groups">{group("Payroll",payroll)}{group("Sales",sales)}{group("Referral Agents",["Referral Agency Invoices","Referral Agency Invoices Create Individual PDF Files","Referral Agency Payments"])}{group("Tracking",["Office Staff Hours"])}{group("Accounting",["Accounting Reports"])}<div className="report-documents"><select aria-label="View Document"><option>&lt;View Document&gt;</option></select><button onClick={()=>setMessage("No document is selected.")}>Edit</button></div><div className="report-extra">{["Website Access","Alerts","Employees with Pay Rate and Referral Agency","Record of Deposits to be Made"].map(button)}</div></div>{message&&<p role="status">{message}</p>}</section>;}
