"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
const flags=["NOI-S","NOI-B","NOC-S","NOC-B"];
export function LienSummaryScreen({generatedAt}:{generatedAt:string}){
  const router=useRouter();const [zoom,setZoom]=useState("100");
  const timestamp=new Date(generatedAt).toLocaleString("en-US",{timeZone:"Asia/Manila",weekday:"long",year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit"});
  function flagHeaders(group:string){return flags.map(flag=><th className="lien-flag" key={group+flag} scope="col" aria-label={`${group} ${flag}`}>{flag.split("").map((letter,i)=><span key={i}>{letter}</span>)}</th>);}
  return <section className="lien-summary"><div className="lien-preview-toolbar"><button onClick={()=>window.print()}>Print / Save PDF</button><button onClick={()=>router.refresh()}>Refresh</button><label>Zoom <select value={zoom} onChange={e=>setZoom(e.target.value)}>{["75","100","125"].map(v=><option key={v} value={v}>{v}%</option>)}</select></label><button onClick={()=>router.push("/tracking")}>Close Preview</button></div><div className="lien-preview-scroll"><article className="lien-paper" style={{zoom:Number(zoom)/100}} aria-label="Seamus Lien Summary print preview"><header><h1>Seamus Lien Summary</h1><time dateTime={generatedAt}>{timestamp}</time></header><table><colgroup>{[0,1].map(i=><col className="lien-wide" key={i}/>)}{flags.map(f=><col className="lien-narrow" key={`customer-${f}`}/>)}<col className="lien-wide"/><col className="lien-wide"/>{flags.map(f=><col className="lien-narrow" key={`gc-${f}`}/>)}<col className="lien-wide"/><col className="lien-wide"/>{flags.map(f=><col className="lien-narrow" key={`owner-${f}`}/>)}</colgroup><thead><tr><th scope="col">Job</th><th scope="col">Customer</th>{flagHeaders("Customer")}<th scope="col">GC Name</th><th scope="col">GC Address</th>{flagHeaders("GC")}<th scope="col">Owner Name</th><th scope="col">Owner Address</th>{flagHeaders("Owner")}</tr></thead><tbody><tr><td colSpan={18} className="lien-empty">Lien report data is unavailable. The Seamus source query, job selection rules, and NOI/NOC field mappings have not been connected.</td></tr></tbody></table><footer>Page 1 of 1</footer></article></div></section>;
}
