"use client";
import { useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import type { OperationalReportRow } from "@/lib/operationalReports";
import { trackingCsv } from "@/lib/trackingGrid";

export function OperationalReportScreen({title,rows,error="",variant}:{title:string;rows:OperationalReportRow[];error?:string;variant:"noc"|"noi"|"rates"|"bonus"}){
 const router=useRouter();const[query,setQuery]=useState("");const[view,setView]=useState("View 01");const[message,setMessage]=useState("");const columns=useMemo(()=>Array.from(new Set(rows.flatMap(Object.keys))).filter(k=>k!=="id"),[rows]);
 const visible=useMemo(()=>rows.filter(r=>!query||Object.values(r).join(" ").toLowerCase().includes(query.toLowerCase())),[rows,query]);
 function save(){localStorage.setItem(`${variant}-report-view`,JSON.stringify({view,query}));setMessage("View saved on this computer.");} function exportRows(){const csv=trackingCsv(columns,visible.map(r=>columns.map(c=>r[c]??"")));const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download=`${variant}-report.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className={`access-report-screen operational-report operational-report-${variant}`}><header><h1>{title}</h1><label>View: <select value={view} onChange={e=>setView(e.target.value)}>{Array.from({length:variant==="noc"?17:8},(_,i)=><option key={i}>{i===0?"01 Default":`View ${String(i+1).padStart(2,"0")}`}</option>)}</select></label><button onClick={save}>Save View</button><button onClick={()=>{localStorage.removeItem(`${variant}-report-view`);setMessage("Saved view deleted.");}}>Delete View</button><button onClick={()=>router.refresh()}>Refresh</button>{variant!=="noc"&&<><button onClick={()=>setQuery("")}>Zero</button><button disabled={!visible.length} onClick={exportRows}>Export View</button></>}<button onClick={()=>router.push("/tracking")}>Cancel</button></header><div className="operational-tools"><label>{variant==="rates"?"Search in Customer:":variant==="bonus"?"Name:":"Search in Name:"}<input value={query} onChange={e=>setQuery(e.target.value)}/></label><div>{Array.from({length:variant==="noc"?17:5},(_,i)=><button key={i} onClick={()=>setView(`View ${String(i+1).padStart(2,"0")}`)}>{i===0?"Default":`View ${String(i+1).padStart(2,"0")}`}</button>)}</div><button onClick={()=>setQuery("")}>Clear Filters</button></div>{variant==="rates"&&<p className="operational-note">The selected tracking week supplies employee pay, bill rate, margin, insurance, and expense values.</p>}{variant==="bonus"&&<p className="operational-note">Bonus totals use the current $1-per-tracked-hour rule shown in the Access report. Referral-specific fields require their source column to be confirmed.</p>}{(error||message)&&<p className="report-data-error" role={error?"alert":"status"}>{error||message}</p>}<div className="operational-grid"><table><thead><tr><th />{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{visible.map((r,i)=><tr key={String(r.id??i)} className={i===0?"is-current":undefined} onDoubleClick={()=>variant==="bonus"&&router.push(`/employees/${r.id}`)}><td />{columns.map(c=><td key={c}>{typeof r[c]==="number"&&(c.includes("Amount")||c.includes("Payment")||c.includes("Balance")||c.includes("Rate")||c.includes("Owed")||c.includes("Bonus")||c==="Margin $")?Number(r[c]).toLocaleString("en-US",{style:"currency",currency:"USD"}):r[c]}</td>)}</tr>)}{!visible.length&&<tr><td colSpan={columns.length+1}>No records match the current filters.</td></tr>}</tbody></table></div><footer>Record: {visible.length?1:0} of {visible.length}</footer></section>;
}
