"use client";
import{useRouter}from"next/navigation";import{useMemo,useState}from"react";import{AccessButton}from"@/components/access/AccessButton";
type Mode="licenses"|"interview"|"osha"|"resume"|"smartphone"|"face";
const ROWS=[
 ["Intelligent Design & Build, LLC","Eamon O'Hara","92 Sewall (Beltramn Inn)","Aguinaldo","","Martins..","","6/12/2026","C","Laborer","N/A"],
 ["Sleeping Dog Properties Inc.","Eamon O'Hara","Louisburg Sq","Alan","","Alves..","","5/5/2023","Z","Laborer","N/A"],
 ["Adzemen Demolition Inc.","Y G","Calare","Alerson","","Silva Pascoal..","","6/9/2023","C","Laborer","N/A"],
 ["Electrical Design and Control Inc","Eamon O'Hara","Rye","Alex","P","Gobeil","","8/1/2025","A","Electrician","Licensed"],
 ["Ithaka Contracting and Design","Eamon O'Hara","Cambridge","Alex","","Maia..","","10/17/2025","B","Laborer","N/A"],
 ["Ahc Mechanical Contractors Inc","Ryan O'Neill","MIT","Alex","Y","Morales","","7/24/2026","B","Plumber","Lic Apprentice"],
 ["Agilitas Energy, Inc.","Ryan O'Neill","Auburn","Alex","","Perlera..","","8/4/2023","C","Laborer","N/A"],
 ["Industrial Power Group, Inc.","","Office","Alison","C","Mc Veigh","","7/24/2026","A","Office","Licensed"],
 ["Piquette & Howard Electric Services Inc","House House","Bake N Joy","Altin","","Koci..","","7/24/2026","A","Electrician","N/A"],
 ["Lothrop Companies, Inc","Eamon O'Hara","018-26 THTFRMS","Amarildo","","Ribeiro..","","4/17/2026","Z","Laborer","N/A"],
 ["KW Management Inc.","House House","Mission Hill","Andre","","Chavez..","","7/24/2026","Z","Laborer","Lic Apprentice"],
 ["Supereon, LLC","Eamon O'Hara","US Army Natick Soldier Systems","Andre","","Lauzier","","2/14/2025","B","Electrician","Apprentice"],
 ["All-State Power And Controls, Inc","Eamon O'Hara","Woburn Bowling","Andrew","M","Kosterman","","7/24/2026","A","Electrician","Licensed"],
 ["Pro Star Energy LLC","Eamon O'Hara","Belfast","Andrew","J","Legere","","9/13/2024","A","Electrician","Licensed"],
 ["Pro Star Energy LLC","Eamon O'Hara","Carver (Rochester Rd.)","Anthony","","Hernandez..","","7/11/2025","A","Electrician","Licensed"],
 ["Elm Electrical Inc","Eamon O'Hara","Easthampton PO#84825","Anthony","E","Paton","","12/2/2022","A","Electrician","Licensed"],
 ["New England Clean Energy","Ryan O'Neill","S. Boston Solar Array removal","Arnaldo","","Pinto..","","12/13/2024","C","Laborer","N/A"],
 ["S.E. & D. Inc (Street)","Ryan O'Neill","Wilmington","Arnaldo","","Torres","","7/24/2026","B","Electrician","Lic Apprentice"],
 ["Harrison Brown Construction, LLC","Ryan O'Neill","Cambridge PO#21147","Baba","","Dembele..","","10/27/2023","C","Laborer","N/A"],
 ["Thomas J Kennedy Plumbing, Heating & H","Ryan O'Neill","Hyde Park","Benjamin","J","Rossetti","","7/17/2026","A","HVAC / Sheet Metal","N/A"],
 ["Intelligent Design & Build, LLC","Eamon O'Hara","267 Tappan St","Bernado","","Santana..","","4/11/2025","C","Laborer","N/A"],
 ["North Shore Mechanical Contractors","Ryan O'Neill","Zealand Pharma","Brad","D","Barba","","7/24/2026","B","Plumber","N/A"],
 ["Mark Richey Woodworking & Design Inc","Ryan O'Neill","Mark Richey Warehouse","Brendon","","Kerche..","","2/27/2026","C","Laborer","N/A"],
 ["Interstate Electrical ( Construction )","House House","Symbotic Tech PO#182473","Brian","J","Lim","","7/24/2026","A","Electrician","Licensed"],
] as const;
const META={licenses:{title:"Employee Licenses",filter:"Status",view:"01 Default Employee Licenses"},interview:{title:"Interview Questions",filter:"Interview Questions",view:"01 Default Interview Questions"},osha:{title:"OSHA",filter:"OSHA",view:"01 Default OSHA"},resume:{title:"Resume or Work History",filter:"Resume or Work History",view:"01 Default Resume or Work History"},smartphone:{title:"Smart Phone",filter:"Smart Phone",view:"01 Default Smart Phone"},face:{title:"Face Meeting",filter:"Face Meeting",view:"01 Default Face Meeting"}};
export function EmployeeDocumentReportScreen({mode}:{mode:Mode}){const router=useRouter();const[search,setSearch]=useState("");const[filter,setFilter]=useState(mode==="licenses"?"Assigned":"");const[selected,setSelected]=useState<Set<number>>(new Set());const m=META[mode];const rows=useMemo(()=>ROWS.filter(r=>!search||`${r[3]} ${r[5]}`.toLowerCase().includes(search.toLowerCase())),[search]);const base=["","Customer",...(mode==="licenses"?["Salesman"]:[]),"Job","Em First Name","MI","Em Last Name","Cell","Week Ending"];
 const special=mode==="licenses"?["Trade","Qualification","Licensed State","License Exp Date","License Copy On File","License Notes","S L C","App Front Desk Note"]:mode==="interview"?["Interview Questions","S L C","Interview Question Notes","Payroll Co","App Front Desk Note"]:mode==="osha"?["OSHA","S L C","Payroll Co","OSHA Notes","App Front Desk Note"]:mode==="resume"?["Resume or Work History","S L C","Resume or Work History Notes","Payroll Co","App Front Desk Note"]:mode==="smartphone"?["Smart Phone","S L C","Payroll Co","App Front Desk Note","Assignment User Name","Assignment Timestamp"]:["Face Meeting","S L C","Payroll Co","App Front Desk Note","Assignment User Name","Assignment Timestamp"];
 return <section className="ac-employee-doc"><header><h1>{m.title}</h1><div><label>View:</label><select><option>{m.view}</option></select><AccessButton>Save View</AccessButton><AccessButton>Delete View</AccessButton><label>Go To:</label><select><option/></select><AccessButton>Refresh</AccessButton></div><aside><AccessButton onClick={()=>router.push("/tracking")}>Cancel</AccessButton><button aria-label="Help">?</button></aside></header><div className="employee-doc-tools"><label className="search">Search in Employee:<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="filter">{m.filter}<select value={filter} onChange={e=>setFilter(e.target.value)}><option>{mode==="licenses"?"Assigned":""}</option><option>Yes</option><option>No</option></select></label><div><span>Select:</span><AccessButton onClick={()=>setSelected(new Set(rows.map((_,i)=>i)))}>All</AccessButton></div></div><div className="employee-doc-grid-wrap"><table className={`legacy-report-grid employee-doc-grid is-${mode}`}><thead><tr>{[...base,...special].map((c,i)=><th key={i}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=>{const common=mode==="licenses"?[r[0],r[1],r[2],r[3],r[4],r[5],r[6],r[7]]:[r[0],r[2],r[3],r[4],r[5],r[6],r[7]];const value=mode==="interview"?(i%5===2?"Yes":"No"):mode==="osha"?(i%3===0?"NAL":i%6===1?"OF":""):mode==="resume"?(i===23?"Yes":"No"):mode==="smartphone"?(i%6===0?"Yes":""):(i===17||i===23?"Yes":"No");const tail=mode==="licenses"?[r[9],r[10],i%5===2?"MA":"",i%6===0?"7/31/2019":"",i%6===0?"Yes":"",i%6===0?"10741 B":"",""]:[value,"",mode==="interview"&&i===7?"This is a test":"","","",""];return <tr key={`${r[0]}-${r[2]}`} className={i===0?"is-current":undefined} onClick={()=>setSelected(old=>{const n=new Set(old);if(n.has(i))n.delete(i);else n.add(i);return n})}><td>{selected.has(i)?"✓":""}</td>{common.map((v,c)=><td key={`c${c}`}>{v}</td>)}{tail.map((v,c)=><td key={`t${c}`}>{v}</td>)}</tr>})}</tbody></table></div></section>}
